import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Slapcommands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Slapcommands</h1>

        <p className={styles.description}>
          Slapcommands is a collection of{" "}
          <a href="https://slapdash.com/">Slapdash</a> custom commands. You can
          find the{" "}
          <a href="https://github.com/AnishDe12020/slapcommands">
            GitHub Repository for this project here
          </a>
        </p>
        <p className={styles.wip}>
          Note: This website is still work-in-progress 🚧
        </p>
      </main>
    </div>
  );
};

export default Home;
